language: python
python:
  - "3.9"

install: "pip install -r requirements.txt"

script:
  - py.test src/tests -svv --cov-report=term-missing --cov-report=html --cov-report=xml --cov=src --tb=short
  
after_success:
  - codecov
