# Generated by Django 3.2.9 on 2021-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="reminder_day",
            field=models.DateField(null=True),
        ),
    ]
